name: Insertar registros en MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar entorno de MySQL
      uses: docker/setup-mysql@v1
      with:
        mysql-version: '5.7'
        mysql-host: ${{ secrets.MYSQL_HOST }}
        mysql-port: ${{ secrets.MYSQL_PORT }}
        mysql-username: ${{ secrets.MYSQL_USERNAME }}
        mysql-password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Insertar registros en la base de datos
      run: |
        mysql -h ${{ secrets.MYSQL_HOST }} -P ${{ secrets.MYSQL_PORT }} -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "USE nombre_de_la_base_de_datos; INSERT INTO tabla (campo1, campo2, campo3) VALUES ('valor1', 'valor2', 'valor3'); INSERT INTO tabla (campo1, campo2, campo3) VALUES ('valor4', 'valor5', 'valor6'); INSERT INTO tabla (campo1, campo2, campo3) VALUES ('valor7', 'valor8', 'valor9');"
